project:
  version: effnet_1shot

model:
  pretrained: true

train:
  head_epochs: 3
  finetune_epochs: 15
  loss: bce

infer:
  checkpoint_path: artifacts/runs/00_baselines_and_early/effnet_1shot/checkpoints/best.pt
