project:
  version: v14_ibn

model:
  use_mixstyle: false
  use_ibn: true

train:
  loss: focal
  focal_gamma: 0.0
  focal_alpha: 0.75
  head_epochs: 3
  finetune_epochs: 20
  warmup_epochs: 3
  backbone_learning_rate: 0.00004
  pretrained_backbone_path: artifacts/checkpoints/v9_fda/best.pt

infer:
  checkpoint_path: artifacts/checkpoints/v14_ibn/best.pt
  threshold: 0.5
