project:
  version: v15_fda_a10

data:
  train_exclude_domains: []
  use_fda: true
  fda_alpha: 0.10

train:
  loss: focal
  focal_gamma: 0.0
  focal_alpha: 0.75
  head_epochs: 0
  finetune_epochs: 15
  backbone_learning_rate: 0.00004
  pretrained_backbone_path: artifacts/runs/02_domain_generalization/v7_messidor_train/checkpoints/best.pt

infer:
  checkpoint_path: artifacts/runs/02_domain_generalization/v15_fda_a10/checkpoints/best.pt
  threshold: 0.5
