project:
  version: v24_multitask

model:
  use_aux_seg: true
  aux_seg_block: 2

train:
  loss: focal
  focal_gamma: 2.0
  focal_alpha: 0.75
  head_epochs: 0
  finetune_epochs: 15
  backbone_learning_rate: 0.00004
  lambda_aux_seg: 0.3
  pretrained_backbone_path: artifacts/runs/03_resolution_layercam/v7_512_messidor_train/checkpoints/best.pt

infer:
  checkpoint_path: artifacts/runs/04_lesion_supervision/v24_multitask/checkpoints/best.pt
  threshold: 0.42
  gradcam_method: layercam
