project:
  version: v6_gamma_only

model:
  use_mixstyle: false

train:
  loss: focal
  focal_gamma: 2.0
  head_epochs: 0
  finetune_epochs: 15
  backbone_learning_rate: 0.00004
  pretrained_backbone_path: artifacts/checkpoints/v4.1/best.pt

infer:
  checkpoint_path: artifacts/checkpoints/v6_gamma_only/best.pt
