project:
  version: v8_mixstyle

data:
  train_exclude_domains: []

train:
  loss: focal
  focal_gamma: 0.0
  focal_alpha: 0.75

infer:
  checkpoint_path: artifacts/runs/02_domain_generalization/v8_mixstyle/checkpoints/best.pt
  threshold: 0.09
