services:
  # AI 백엔드 서비스
  backend:
    build: 
      context: ./backend
      dockerfile : backend_Dockerfile
    container_name: eye-backend-service
    ports:
      - "8000:8000"
    volumes:
      # 백엔드 소스 코드 동기화 (Hot Reload 대용)
      - ./backend:/app
      # AI 모듈, configs, 데이터, 아티팩트 (git 미추적)
      - ./ai:/ai
    environment:
      - PYTHONUNBUFFERED=1
    restart: always



  # Flutter 프론트엔드 서비스
  frontend:
    build: 
      context: ./frontend
      dockerfile: frontend_Dockerfile
    container_name: flutter-web-client
    ports:
      - "8080:80"  # 윈도우 브라우저에서 localhost:8080으로 접속
    depends_on:
      - backend
    restart: always

networks:
  default:
    name: eye-project-network